// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResultR.VSToolkit
{
    internal sealed partial class Vsix
    {
        public const string Id = "ResultR.VSToolkit.858ccf1c-9417-403d-a2ad-bd848e824963";
        public const string Name = "ResultR VS Toolkit";
        public const string Description = @"ResultR VS Toolkit lets you instantly navigate from IRequest to IRequestHandler with a keystroke or right-click. Scaffold new request/handler pairs with correct namespaces from Solution Explorer.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Alan Barber";
        public const string Tags = "resultr, cqrs, mediator, request-handler, result-pattern";
        public const bool IsPreview = false;
    }
}
