// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResultR.VSToolkit
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ResultRVSToolkitString = "34fed52c-3d19-4b03-9515-023c3dfe0eb7";
        public static Guid ResultRVSToolkit = new Guid(ResultRVSToolkitString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GoToHandlerCommand = 0x0101;
        public const int GoToHandlerGroup = 0x1000;
        public const int AddRequestHandlerCommand = 0x0102;
        public const int AddRequestHandlerGroup = 0x1001;
        public const int AddRequestHandlerFolderCommand = 0x0103;
        public const int AddRequestHandlerFolderGroup = 0x1002;
    }
}
